[package]
name = "foundry-benchmarks"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
dotenvy = "0.15"
eyre = "0.6"
rayon = "1.10"
yansi = "1.0"
tempfile = "3.20"
